### PR TITLE
Pull commits from the author's repo

### PR DESCRIPTION
**Pull request by rshym**
All commits (except the first "Initial commit") were moved from https://github.com/dterletskiy/lisot/commits/main/ as-is according to the state on May 10, 2024.

List of the original commits (the latest is the first):
```
69434da84af1a719714dc83246249e9a19c8fdbf Change project LICENSE from "MIT" to "Apache 2.0"
469ab57003cf7916523bad0a766c54edade3717e Code refactoring.
dac7263d0f9ff4ff2ac88eef7167cf9389e0d92c Implement support for choosing interface name for client to be used to connet to server. Parameter "--interface" implemented for client.
82b0cb124fbe8d0954d1f1f11b315c76ce4b1b0c Add possibility to build lisot as part of AOSP (#2)
55da52d25011aa4d31ead58dd66510c8a93d60de Makefile: fixed wrong installation path (#1)
de71f8e0128e0138017f485b2abedbfc0670a841 Fix wrong address detection for UNIX socker. There was pointer to temporaty object what is destroyed before pointer usage.
796944e5851cc4cac5c882d0a4dd28e8587b1a72 Fix compilation warnings.
c8ea156291c422a63b8453408ef17e4c1521d7bc Fix build error.
bb2e3e52a71a49678a4f71407aa1c3ae0c06d9f7 Adapt Makefile to have a possibility to compile with sourcesed sysroot for cross-compilation.
09b3cd29725baff861d1b4528af55c8d43aef625 Fix crash during sending message with random text and defined length.
a31f1d1f1ce2d3d1fba60959fd574836ddc35c5d Trace message refactoring.
8627d2799e4cf2d50b2fe5d166fc132e5c955409 Trace system.
e9062966ea20dcc918c6a2cb2d02d65626c57960 initial implementation
```

### CODE REVIEW

**Comment by rshym** [comment]
Despite these commits being moved as-is for reference, I could propose changing the formatting of some commit messages:
- add a separator between the head and body
- add author's sign-of
- reword some commit messages to fit into 60 symbols
- add message body for a few commit messages

No other changes are supposed to be made.

**Comment by rshym** [comment]
@lorc @dterletskiy, what do you think regarding the minor reformatting of the commit messages mentioned above?

**Comment by dterletskiy** [comment]
For me is OK

**Comment by rshym** [comment]
> For me is OK

@dterletskiy if you have no objections, I will make a little re-formatting of the commit messages according to our rules for commit messages, as described in https://github.com/lorc/xen-troops.github.io/blob/pr_process/process/process.md
This document is under review but is approved in general.
The main idea behind these changes - is to have a unified approach to all repos across the organization. No action is needed from your side, I will make a rewording and will write a detailed comment with all made changes to commit messages.

**Comment by lorc** [comment]
I'm fine as well.

**Comment by rshym** [comment]
Commit messages are reworded and reformatted. No changes to sources were made.

Please see below the modified parts of the messages. Commits are separated by the `=====`, and original/modified messages are separated by the `---`.
Only modified commits are listed.

```
=====

Change project LICENSE from "MIT" to "Apache 2.0"
Provided SPDX-Identifier in source code.
---
Add SPDX-Identifiers

Provide SPDX-Identifier in source code.

=====

Code refactoring.
---
Code refactoring

- update .gitinfo
- update README.md
- rework code for the client and the server

=====

Implement support for choosing interface name for client to be used to connet to server.
Parameter "--interface" implemented for client.

Implement "info" subtool for listing existing interfaces.
---
Add possibility to select interface

Implement support for choosing interface name for client
to be used to connet to server.
Parameter "--interface" implemented for client.
Implement "info" subtool for listing existing interfaces.

=====

Fix wrong address detection for UNIX socker.
There was pointer to temporaty object what is destroyed before pointer usage.
---
Fix wrong address detection for UNIX socket

There was pointer to temporaty object what is destroyed before pointer usage.

=====

Fix compilation warnings.
---
Fix compilation warnings

This commit resolves compilation warnings.

=====

Fix build error.
---
Add missed `.value()` to the iterator

This commit fixes the build error.

=====

Adapt Makefile to have a possibility to compile with sourcesed sysroot for cross-compilation.
---
Use an external sysroot during the build

Adapt Makefile to have a possibility to compile with
the sourcesed sysroot for cross-compilation.

=====

Fix crash during sending message with random text and defined length.
---
Fix crash in the sending of the massage

Fix crash during sending message with random text and defined length.

=====

Trace message refactoring.
---
Trace message refactoring

=====

Trace system.
---
Add trace system

=====

initial implementation
---
Initial implementation

README.md was updated accordingly.

Signed-off-by: Dmytro Terletskyi <dmytro_terletskyi@epam.com>

=====
```

**Comment by dterletskiy** [comment]
For me looks good.

**Pull request merged**
